### ISSUE TITLE
CSV content is not showing from my agenda

### ISSUE THREAD

**Issue by map7** [atheriel/org-clock-csv#1]
I just installed org-clock-csv and ran M-x org-clock-csv, it took me to a new buffer with the headings task,category,start,end,effort,ishabit,tags but never filled out the data.

I've got all my org files in my ~/org and ~/org/business directories and I add these like so;

;; Org-mode options
(add-hook 'org-mode-hook 'turn-on-visual-line-mode)
(setq org-clock-out-remove-zero-time-clocks t)
(setq org-directory "~/org")
(setq org-agenda-files '("~/org/" "~/org/business"))

My full setup is at: https://github.com/map7/emacs-config 
My setup is pretty big so it might be something to do with my setup which is not yet compatible with your plugin.

Let me know how I can supply more information to get it working.

**Comment by atheriel** [comment]
Actually I think it's a simpler problem: I didn't realize that `org-agenda-files` could contain directory entries. I'll have to update the logic that opens the files to use the function instead of the variable.

Can you try running it on a single file, e.g.

``` elisp
(org-clock-csv "~/org/example.org")
```

and see if you get any results?

**Comment by atheriel** [comment]
@map7 Might take a little bit for the latest commit to percolate through to MELPA, but let me know if it works when it does.

**Comment by map7** [comment]
It works now. It's not including my archived timesheets though.
Sometimes I archive into the defined org-archive area (another directory).

**Comment by atheriel** [comment]
`org-agenda-files` excludes archived files by default, which I don't think I will override. However, you should be able to get all items (including the archived ones) by running

``` elisp
(org-clock-csv (org-agenda-files nil t))
```

i.e using the output of `org-agenda-files` as the file list directly.
