### ISSUE TITLE
How do I gather entries from all org agenda files?

### ISSUE THREAD

**Issue by concretevitamin** [atheriel/org-clock-csv#13]
Hi,

Thanks for the great package.  I'm currently using the following:
```
/Applications/Emacs.app/Contents/MacOS/Emacs \
    --batch -l package \
    --eval "(package-initialize)" \
    -l ./org-clock-csv.el -f org-clock-csv-batch-and-exit \
    ~/org/work.org \
    >work.csv
```
However, I'd like to gather & export entries from all agenda files, not just one (shown as `~/org/work.org` above).  Is there a way to do that?  (My Emacs setup is Spacemacs by the way.)

**Comment by atheriel** [comment]
You should be able to pass multiple org files (that is, instead of `~/org/work.org` you'd write `~/org/work.org ~/org/home.org`). Is that what you're after?

**Comment by concretevitamin** [comment]
```
/Applications/Emacs.app/Contents/MacOS/Emacs -batch -l ~/.emacs.d/init.el -l ./org-clock-csv.el --eval "(run-hooks 'emacs-startup-hook)" -f org-clock-csv-batch-and-exit  2>/dev/null 
```
works for me now.

**Comment by atheriel** [comment]
Ah, so you've set `org-agenda-files` somewhere in your configuration, and are loading that. Nice to see a working example.
