### ISSUE TITLE
Add a formatter that would return an org table

### ISSUE THREAD

**Issue by Fuco1** [atheriel/org-clock-csv#15]
And then for maximum awesome add an org dblock: https://orgmode.org/manual/Dynamic-blocks.html (could take formatter as argument).

This would allow exporting the clock data to org for further processing with tables/babel etc...

I have my own hack in my config but this would be much better.  And since you already  support customization in the formatters maybe we could provide a bunch by default.

**Comment by Fuco1** [comment]
Side question: not sure what to do with the header though.  It would probably make sense to change it from a string to a list of strings and then join it in the formatter with the split character.  Or it should be part of the formatter (since now you have to keep them in sync anyway so is there any reason to have it customizable separately?)

**Comment by atheriel** [comment]
Does the regular clock table not support something that the CSV format does?

**Comment by Fuco1** [comment]
@atheriel The regular clock table does not return each entry but aggregates it by subtrees.  I'm not aware of some setting that would give me raw data.

I might want to for example group by day, I haven't found a way to do that.

**Comment by atheriel** [comment]
I'm going to declare this "out of scope" for this particular package, which is intended to focus narrowly on export to CSV. However, feel free to reuse some of the internal machinery to implement the dynamic block; I can see the appeal for those who'd like to work entirely in Org mode.
