### ISSUE TITLE
Exporting the values of properties?

### ISSUE THREAD

**Issue by georgewsinger** [atheriel/org-clock-csv#23]
**Context.** In addition to tracking timelog data, I also track the `:UTILITY:` property for `CLOSED` tasks. So for example the following

    * Open Task
          :PROPERTIES:
          :UTILITY:        0.75μ
          :END:
    * COMPLETE Closed Task
          CLOSED: [2019-07-09 Tue 16:17]
          :PROPERTIES:
          :UTILITY:        0.5μ
          :END:
          :LOGBOOK:
          CLOCK: [2019-07-09 Tue 00:00]--[2019-07-09 Tue 00:20] =>  0:20
          :END:

shows `0.5μ` of utility for CLOSED tasks.

**Question:** Is there a way to use `org-clock-csv` to export this sort of data? I suppose the important things to export are (i) whether a task is CLOSED (and if so what at what date); (ii) capturing the value of arbitrary properties (in this case `:UTILITY:`). I can use my own parsing logic to interpret the rest.

**Comment by atheriel** [comment]
It is not currently possible to access all task properties. However, it's likely that the parser could be extended to make all properties available, and I'm open to adding this feature.

**Comment by georgewsinger** [comment]
Is this a hard feature to implement?

**Comment by atheriel** [comment]
I don't think so, it will just require a little sleuthing to see how `org-element` returns the properties. Feel free to take a crack at it.

**Comment by atheriel** [comment]
Closed by #30.
