### ISSUE TITLE
Collect TITLE

### ISSUE THREAD

**Issue by gscano** [atheriel/org-clock-csv#26]
The `task` and `parents` columns do no include any information about the file from which they originate. Because the filename or the TITLE can de facto be used as a structuring level on top of the headlines I think such information should be included in the output.

I am ready to send a PR, optionally adding the TITLE (or the filename in case there are no TITLE) as the first item in the `parents` column.
However, I would like to check with you if:
1) there would be any general interest in this;
2) the information should be reported in front of the `parents` column or if a new `title` column should be used.

In any case, I think that leaving the feature as optional and defaulting to not reporting this information would be the best option to not break any script using the csv output.

Thanks in advance.

**Comment by atheriel** [comment]
I believe this would have the same implementation issue as #5, but if you can think of a way to do it I believe it would be a desirable feature. As for where to put it: add it as a new field to start.

**Comment by gscano** [comment]
Thanks for merging.
