### ISSUE TITLE
Minimal required org-version

### ISSUE THREAD

**Issue by flyck** [atheriel/org-clock-csv#4]
Hey,

This package seems to require an org-version higher than 8.2. Could this get included into the code?

With my initial setup this package stopped with the error that it cant find "(org-element-lineage current)". After upgrading to org-version 9.* from elpa using the package-manager it now works like a charm.

**Comment by atheriel** [comment]
Sorry for the delay on this. I've added the dependency to the package metadata, which should make its way through MELPA shortly.
