### ISSUE TITLE
Should Category inherit from #+CATEGORY ?

### ISSUE THREAD

**Issue by jackbaty** [atheriel/org-clock-csv#5]
Most of my org docs contain a top-level #+CATEGORY declaration. The output after running org-clock-csv does not seem to pick this up (the Category column is always empty). 

If I set a :CATEGORY: property on a single node it _is_ included in the output. Would it be possible/useful for the output to use the inherited Category value?

This may also help with the issue raised in #3

**Comment by atheriel** [comment]
To break the silence on this issue: this is a desirable feature. Unfortunately, the `org-element` API makes it a bit difficult to pull off; see [my comment in the code for determining the category](https://github.com/atheriel/org-clock-csv/blob/master/org-clock-csv.el#L125-L130) for details.
