### ISSUE TITLE
More descriptive usage documentation?

### ISSUE THREAD

**Issue by lwjohnst86** [atheriel/org-clock-csv#8]
Thanks for making this package! Could you describe how to use this package a bit more? Targeted to non-emacs wizards (aka myself)? I understand how to do `org-clock-csv` via `M-x`. However, I want to run the `org-clock-csv-batch` command on a specific file via the terminal/command-line. What are the exact commands/process to use to do this?

**Comment by atheriel** [comment]
Thanks for the interest! Unfortunately, `org-clock-csv-batch` is currently pretty unstable, so I would not recommend using it right now. The goal is to have it run something like an `ert` test suite, e.g.

    $ emacs --batch -l org-clock-csv -f org-clock-csv-batch "todo.org" > todo.csv

But I haven't been able to get this working, and it fell by the wayside. I should have some time to look into it this weekend.

**Comment by lwjohnst86** [comment]
Cool! Thanks :) If I knew some elisp I would offer to help, but alas I do not know it.

**Comment by atheriel** [comment]
@lwjohnst86 Does the new documentation in the README file answer some of your questions?

(You may need to wait for today's commits to get propagated through to MELPA, which might take a few hours.)

**Comment by lwjohnst86** [comment]
Yes! It does work! Thanks so much! :D There was a missing ending `\` in the readme, that I commented on in the commit. 

Thanks again!
